site_name: OpenChirp REST API Documentation
theme: readthedocs
extra_css: [extra.css]
pages:
    - Introduction : index.md
    - Resources : 
        - Location : location.md
        - Gateway : gateway.md
        - Device : device.md
        - Transducer : transducer.md
        - Service : service.md

